# Replace current-theme.conf with your own file or symlink to change themes.
include current-theme.conf

# Defaults are in /etc/xdg/kitty/kitty.conf. Uncommment below to override.
# background_opacity 0.70
# dynamic_background_opacity yes
# font_family JetBrains Mono
