[General]
DisplayServer=wayland

[Wayland]
CompositorCommand=/usr/bin/niri --config /usr/share/pond-interface/lockscreen/greeter/niri.kdl

[Theme]
ThemeDir=/usr/share/pond-interface/lockscreen
Current=greeter
